### PR TITLE
fix: Fixes for multiple issues identified by adding flag tests

### LINKED ISSUE #1658: bug: --tfvars-file flag is not working anymore
**Describe the bug**

When executing `tfsec` with `--tfvars-file` flag, it's no able to find the file passed by

```bash
$ ls -l1                                                                                                                                                                                                                         
README.md
cloud-build
cloud-build.tf
cloud-build.tfvars
github.tf
github.tfvars
include
locals.tf
modules
project.tf
settings.tf
storage.tf
variables.tf

$ tfsec --tfvars-file github.tfvars                                                                                                                                                                                              
Scan error: failed to load tfvars from github.tfvars: open //github.tfvars: no such file or directory

$ tfsec --version                                                                                                                                                                                                               
v1.16.2
```

**To Reproduce**
1. Create a custom `whatever.tfvars` file
2. Execute `tfsec` passing the above file as an argument
```bash
$ tfsec --tfvars-file whatever.tfvars
```

**Expected behavior**
Scan the `.tfvars` file

**Screenshots/Output**
```bash
$ tfsec --tfvars-file github.tfvars                                                                                                                                                                                              
Scan error: failed to load tfvars from github.tfvars: open //github.tfvars: no such file or directory
```

**System Info**
<!-- complete the following -->
 - tfsec version: `v1.16.2`
 - terraform version: `v1.0.11`
 - OS: MacOS, but also not working on Debian 10

**Example Code**
<!-- a minimal terraform example which will help us reproduce the issue (remove anything sensitive first!) -->

**Additional context**
<!-- Add any other context about the problem here. -->

### LINKED ISSUE #1659: question: Can the filename in JSON report be relative to the project?
Hello,

I have a business requirement as the following;
- We would like to commit the TFSec results in JSON format in our code repository.
- Whenever another developer runs TFSec on their local, this file will be updated to see the new issues if exists easily.

At the moment, this works fine but with one issue. The **location.filename** parameter in the JSON file contains the full path of the user include also **/home/$username/$project-location/...**

Right now we are excluding filename completely with piping with`jq 'del(.. | .filename?)'` but it makes it harder to locate which file contains the issues.

So, my question is that is there a way to run TFSec with JSON natively to contain relative path to the application without computer specific project path or would it be possible to add it as a feature?

**Example:**
**Instead of:** `"filename": "/Users/omenevseoglu/IdeaProjects/contosso-project/main.tf"`
**Relative :** `"filename": "~/contosso-project/main.tf"` (or maybe based on where you run tfsec even `~/main.tf` is fine)

**PS:** I really like this project. So, keep up the good work!

Kr

### LINKED ISSUE #1661: bug: tfsec:ignore in modules broken
Since v0.16 support for `tfsec:ignore` seems to be broken in modules.
Here's a short example with two `tfsec:ignore`. The one in the top-level file still works, the one in the `database` module doesn't after `terraform init`.

```shell
✓ 5183$ pwd           
/Users/krei04/test
~/test 
✓ 5183$ ls -alR                     
total 8
drwxr-xr-x    4 krei04  staff   128 Apr  6 14:21 .
drwx------@ 134 krei04  staff  4288 Apr  6 14:22 ..
drwxr-xr-x    3 krei04  staff    96 Apr  6 14:21 database
-rw-r--r--    1 krei04  staff  1263 Apr  6 14:21 main.tf

./database:
total 8
drwxr-xr-x  3 krei04  staff    96 Apr  6 14:21 .
drwxr-xr-x  4 krei04  staff   128 Apr  6 14:21 ..
-rw-r--r--  1 krei04  staff  1206 Apr  6 14:21 main.tf
~/test 
✓ 5184$ cat main.tf          
module "application_db" {
  source = "./database"
}

# tfsec:ignore:aws-rds-enable-performance-insights-encryption
resource "aws_db_instance" "toplevel_db" {
  apply_immediately            = true
  identifier                   = "${var.platform_name}-toplevel-db"
  availability_zone            = "${data.aws_region.current.name}a"
  username                     = "awsrdsdba"
  allocated_storage            = 20
  password                     = var.db_admin_password
  engine                       = "postgres"
  engine_version               = "14.2"
  multi_az                     = false
  instance_class               = "db.t3.micro"
  db_subnet_group_name         = aws_db_subnet_group.db_subnet_group.id
  backup_window                = "00:00-00:30"
  maintenance_window           = "sat:01:00-sat:02:00"
  backup_retention_period      = 7
  storage_encrypted            = true
  vpc_security_group_ids       = [aws_security_group.db_security_group.id]
  skip_final_snapshot          = false
  final_snapshot_identifier    = "${var.platform_name}-final-snapshot"
  allow_major_version_upgrade  = true
  auto_minor_version_upgrade   = true
  publicly_accessible          = false
  copy_tags_to_snapshot        = true
  performance_insights_enabled = true
}
~/test 
✓ 5185$ cat database/main.tf 
# tfsec:ignore:aws-rds-enable-performance-insights-encryption
resource "aws_db_instance" "module_db" {
  apply_immediately            = true
  identifier                   = "${var.platform_name}-module-db"
  availability_zone            = "${data.aws_region.current.name}a"
  username                     = "awsrdsdba"
  allocated_storage            = 20
  password                     = var.db_admin_password
  engine                       = "postgres"
  engine_version               = "14.2"
  multi_az                     = false
  instance_class               = "db.t3.micro"
  db_subnet_group_name         = aws_db_subnet_group.db_subnet_group.id
  backup_window                = "00:00-00:30"
  maintenance_window           = "sat:01:00-sat:02:00"
  backup_retention_period      = 7
  storage_encrypted            = true
  vpc_security_group_ids       = [aws_security_group.db_security_group.id]
  skip_final_snapshot          = false
  final_snapshot_identifier    = "${var.platform_name}-final-snapshot"
  allow_major_version_upgrade  = true
  auto_minor_version_upgrade   = true
  publicly_accessible          = false
  copy_tags_to_snapshot        = true
  performance_insights_enabled = true
}
```

Before running `terraform init` both ignores work:

```shell
~/test 
✓ 5186$ tfsec --exclude-downloaded-modules --concise-output          

No problems detected!
```

After `terraform init`, the ignore in the `database` module no longer works:

```shell
✓ 5187$ terraform init                                     
Initializing modules...
[...]
~/test 
✓ 5188$ tfsec --exclude-downloaded-modules --concise-output

Result #1 HIGH Instance has performance insights enabled without encryption. 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 database/Users/krei04/test/database/main.tf Lines 2-26
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    2  │ resource "aws_db_instance" "module_db" {
    3  │   apply_immediately            = true
    4  │   identifier                   = "${var.platform_name}-module-db"
    5  │   availability_zone            = "${data.aws_region.current.name}a"
    6  │   username                     = "awsrdsdba"
    7  │   allocated_storage            = 20
    8  │   password                     = var.db_admin_password
    9  │   engine                       = "postgres"
   10  │   engine_version               = "14.2"
   11  │   multi_az                     = false
   12  │   instance_class               = "db.t3.micro"
   13  │   db_subnet_group_name         = aws_db_subnet_group.db_subnet_group.id
   14  │   backup_window                = "00:00-00:30"
   15  │   maintenance_window           = "sat:01:00-sat:02:00"
   16  │   backup_retention_period      = 7
   17  │   storage_encrypted            = true
   18  │   vpc_security_group_ids       = [aws_security_group.db_security_group.id]
   19  │   skip_final_snapshot          = false
   20  │   final_snapshot_identifier    = "${var.platform_name}-final-snapshot"
   21  │   allow_major_version_upgrade  = true
   22  │   auto_minor_version_upgrade   = true
   23  │   publicly_accessible          = false
   24  │   copy_tags_to_snapshot        = true
   25  │   performance_insights_enabled = true
   26  │ }
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-rds-enable-performance-insights-encryption
      Impact Data can be read from the RDS Performance Insights if it is compromised
  Resolution Enable encryption for RDS clusters and instances

  More Information
  - https://aquasecurity.github.io/tfsec/v1.16.2/checks/aws/rds/enable-performance-insights-encryption/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#performance_insights_kms_key_id
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_kms_key_id
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


  8 passed, 1 ignored, 1 potential problem(s) detected.
```

Note the file path for the reported issue:  **database**/Users/krei04/test/database/main.tf - this path does not exist and matching with detected ignores might be broken because of this.
(Older tfsec versions had a correct relative path here: `database/main.tf`).

### PR DESCRIPTION
**Pull request by liamg**
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>

Resolves #1661
Resolves #1659
Resolves #1658

### CODE REVIEW

**Review by owenrumney — DISMISSED** [review]

File: internal/pkg/formatter/default.go [hunk 1]
```diff
@@ -133,43 +177,7 @@ func printResult(b formatters.ConfigurableFormatter, group formatters.GroupedRes
...
-						filename:   parentRelative,
-						lineInfo:   parentLineInfo,
-						moduleName: mod.Reference().String(),
-					})
-				}
-			}
-
-		}
-	}
+	filename, _, via := makeFilenameNice(first, b.BaseDir())
```
Comment (owenrumney) [inline internal/pkg/formatter/default.go:180]: thats my kind of function name :-)

**Review by owenrumney — APPROVED** [review]
