### PR TITLE
Provide all checks with the module for the checked block

### LINKED ISSUE #1010: tfsec against tf code using terraform-aws-modules/s3-bucket/aws fails 2 checks
**Describe the bug**
When trying to apply tfsec to terraform code that uses `terraform-aws-modules/s3-bucket/aws`, I can't seem to make it pass the `aws-s3-enable-bucket-encryption` and `aws-s3-specify-public-access-block` checks.  I believe that I have configured the module in such a way that it should pass the checks. 

**To Reproduce**
```
$ terraform --version
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
```

```
$ tfsec --version
0.57.1
```

Create file `main.tf`:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "eu-west-2"
}

resource "aws_kms_key" "objects" {
  description             = "KMS key is used to encrypt bucket objects"
  deletion_window_in_days = 7
  enable_key_rotation     = true
}

module "s3_bucket" {
  source = "terraform-aws-modules/s3-bucket/aws"

  bucket = "my-s3-bucket"
  acl    = "private"

  attach_public_policy    = true
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  logging = {
    target_bucket = "my-log-bucket"
    target_prefix = "log/"
  }

  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = aws_kms_key.objects.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }

  versioning = {
    enabled = true
  }
}
```

Run
```
$ terraform init
$ tfsec .
```

**Expected behavior**
Checks should pass

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04

**Additional context**
None

### PR DESCRIPTION
**Pull request by liamg**
Resolves #1010

### CODE REVIEW

File: internal/app/tfsec/scanner/scanner.go [hunk 1]
```diff
@@ -104,3 +65,41 @@ func (scanner *Scanner) Scan(blocks []block.Block) []result.Result {
 	})
 	return results
```
Comment (owenrumney) [inline internal/app/tfsec/scanner/scanner.go:66]: Nice!

**Review by owenrumney — APPROVED** [review]
