### PR TITLE
fix: tfsec output links for custom checks

### LINKED ISSUE #1512: bug: output formatter isn't picking up links for custom checks
**Describe the bug**

When a custom rule is triggered, the results don't show the expected link from the `relatedLinks` array in the custom check.

**Expected behavior**
The `relatedLinks` array from the custom check should be present in the `links` array in the result.

**Screenshots/Output**
```
    {
      "description": "Custom check failed for resource module.production_application:aws_sns_topic.insecure_3. SNS Topics require encryption",
      "impact": "SNS data will exist in clear text if it is not encrypted",
      "links": [
        "https://aquasecurity.github.io/tfsec/v1.0.11/checks/custom/custom/SB_001/"
      ],
      "location": {
        "end_line": 11,
        "filename": "/tmp/build/437d4812/pull-request/terraform/modules/aws/application/insecure_infrastructure.tf",
        "start_line": 9
      },
      "long_id": "custom-custom-sb_001",
      "resolution": "Add the kms_master_key_id attribute. Use `kms_master_key_id = \"alias/aws/sns\"` for the default AWS-managed key.",
      "resource": "aws_sns_topic.insecure_3",
      "rule_description": "Require encryption for SNS topics",
      "rule_id": "",
      "rule_provider": "custom",
      "rule_service": "custom",
      "severity": "HIGH",
      "status": 0
    },
```
**System Info**

 - tfsec version: `v1.0.11`
 - terraform version: `v0.14.11`
 - OS: `OSX`

**Example Code**
```
# Custom check
---
checks:
- code: SB_001
  description: Require encryption for SNS topics
  impact: SNS data will exist in clear text if it is not encrypted
  resolution: Add the kms_master_key_id attribute. Use `kms_master_key_id = "alias/aws/sns"` for the default AWS-managed key.
  requiredTypes:
  - resource
  requiredLabels:
  - aws_sns_topic
  severity: ERROR
  matchSpec:
    name: kms_master_key_id
    action: isPresent
  errorMessage: SNS Topics require encryption
  relatedLinks:
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic#kms_master_key_id
```

```
resource "aws_sns_topic" "insecure_3" {
  name = "insecure_3"
}
```

### PR DESCRIPTION
**Pull request by gabrielleecredera**
resolves #1512

### CODE REVIEW

File: internal/app/tfsec/cmd/output.go [hunk 1]
```diff
@@ -43,15 +43,23 @@ func gatherLinks(result rules.Result) []string {
...
-			"https://aquasecurity.github.io/tfsec/%s/checks/%s/%s/%s/",
-			v,
-			result.Rule().Provider,
-			strings.ToLower(result.Rule().Service),
-			result.Rule().ShortCode,
-		),
-	}, links...)
+
+	var docsLink []string
+	if result.Rule().Provider == "custom" {
```
Comment (owenrumney) [inline internal/app/tfsec/cmd/output.go:48]:
```suggestion
	if result.Rule().Provider == provider.CustomProvider {
```

Nitpick but can we use the enum

Comment (gabrielleecredera) [reply internal/app/tfsec/cmd/output.go]: ah yes, thanks :)

**Review by owenrumney — APPROVED** [review]
